---
- name: Ensure Docker is installed
  hosts: all
  remote_user: ec2-user
  gather_facts: false
  become: true
  tasks:
    - name: Install Docker
      yum: name=docker

    - name: Ensure docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

- name: Initialize Swarm Mode
  hosts: manager-leader
  remote_user: ec2-user
  gather_facts: false
  become: true
  tasks: 
    - shell: "docker info | grep 'Swarm' | awk -F'Swarm: ' '{print $NF}'"
      register: swarm_mode
      
    - name: Swarm init
      command: docker swarm init --advertise-addr {{ private_ip }}
      when: swarm_mode.stdout == "inactive"